openapi: 3.0.3
info:
  title: ''
  version: 0.0.0
paths:
  /api/parser/{filename}:
    get:
      operationId: api_parser_retrieve
      parameters:
      - in: path
        name: filename
        schema:
          type: string
          pattern: ^[^/]+$
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    post:
      operationId: api_parser_create
      parameters:
      - in: path
        name: filename
        schema:
          type: string
          pattern: ^[^/]+$
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/relatorio/{nome_loja}/:
    get:
      operationId: api_relatorio_retrieve
      parameters:
      - in: path
        name: nome_loja
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    post:
      operationId: api_relatorio_create
      parameters:
      - in: path
        name: nome_loja
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
